# Change these first
owner: perennialtech # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SearXNG
    url: https://searx.perennialte.ch
  - name: 4get
    url: https://4get.perennialte.ch
  - name: Libreddit
    url: https://libreddit.perennialte.ch
  - name: Nitter
    url: https://nitter.perennialte.ch
  - name: Invidious
    url: https://invidious.perennialte.ch
  - name: Rimgo
    url: https://rimgo.perennialte.ch
  - name: Quetre
    url: https://quetre.perennialte.ch
  - name: Rimgo
    url: https://rimgo.perennialte.ch
  - name: AnonymousOverflow
    url: https://overflow.perennialte.ch
  - name: Lingva
    url: https://lingva.perennialte.ch
  - name: PrivateBin
    url: https://privatebin.perennialte.ch

status-website:
  cname: status.perennialte.ch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status — perennialte.ch
  introTitle: "Service Status — perennialte.ch"
  introMessage: This page monitors the liveness and response times of services provided by perennialte.ch. Services are checked every 5 minutes for liveness, while response times are recorded once per day.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - perennialtech
