owner: perennialtech
repo: upptime

sites:
  - name: Main website
    url: https://perennialte.ch/home
  - name: SearXNG
    url: https://searx.perennialte.ch
  - name: 4get
    url: https://4get.perennialte.ch
  - name: Redlib
    url: https://redlib.perennialte.ch
  - name: Nitter
    url: https://nitter.perennialte.ch
  - name: Invidious
    url: https://invidious.perennialte.ch
  - name: Rimgo
    url: https://rimgo.perennialte.ch
  - name: Quetre
    url: https://quetre.perennialte.ch
  - name: Rimgo
    url: https://rimgo.perennialte.ch
  - name: AnonymousOverflow
    url: https://overflow.perennialte.ch
  - name: PrivateBin
    url: https://privatebin.perennialte.ch

status-website:
  cname: status.perennialte.ch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status | perennialte.ch
  introTitle: "Service Status"
  introMessage: This page monitors the liveness and response times of services provided by perennialte.ch. Services are checked every 5 minutes for liveness, while response times are recorded once per day.
  navbar:
    - title: Home
      href: https://perennialte.ch/home
    - title: Services
      href: https://perennialte.ch/services
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow:"

assignees:
  - perennialtech

i18n:
  footer: The source code for this page is available at [GitHub]($REPO). Monitoring is provided by [Upptime](https://upptime.js.org).
